-- Migration 0014: 100 Authentic Pakistani Clothing Products & Lookbook Seed
-- Enriches the D1 database with ~100 luxury Pakistani clothing products across Unstitched Lawn, Winter Khaddar, Ready to Wear Pret, Chiffon Formals, Festive Eid, Silk, Velvet, and Daily Cambric.

-- 1. Ensure Additional Pakistani Fashion Taxonomy Collections
INSERT OR IGNORE INTO categories (id, parent_id, name, slug, description, sort_order, is_active) VALUES
  ('cat_festive', NULL, 'Luxury Festive & Eid', 'luxury-festive-eid', 'Heavy embroidered chiffon and silk formal wear for festive occasions', 40, 1),
  ('cat_chiffon', 'cat_festive', 'Chiffon Formals', 'chiffon-formals', '3-Piece unstitched and ready to wear embroidered chiffon suits', 1, 1),
  ('cat_kurtas', 'cat_ready', 'Embroidered Kurtas & Tunics', 'embroidered-kurtas', 'Stitched ethnic kurtas and daily casual tunics', 1, 1),
  ('cat_daily', NULL, 'Daily Printed Cambric', 'daily-printed-cambric', 'Comfortable printed cambric and cotton daily wear suits', 50, 1);

-- 2. Insert 100 Authentic Pakistani Clothing Products (Lawn, Khaddar, Pret, Chiffon, Velvet, Silk, Cambric)
INSERT OR IGNORE INTO products (id, name, slug, description, base_price_pkr, category_id, is_active, seo_title, seo_description) VALUES
  ('prod_100_01', 'Noorani Embroidered Lawn 3-Piece', 'noorani-embroidered-lawn-3-piece', 'Luxury emerald green lawn suit with zari embroidery and pure silk dupatta.', 7800, 'cat_lawn_3p', 1, 'Noorani Embroidered Lawn | Khaadi & Co', 'Shop luxury 3-piece unstitched lawn suit with silk dupatta.'),
  ('prod_100_02', 'Zeenat Pure Khaddar Ensemble', 'zeenat-pure-khaddar-ensemble', 'Warm winter khaddar 3-piece suit with traditional Kashmiri shawl.', 8900, 'cat_khaddar', 1, 'Zeenat Pure Khaddar | Khaadi & Co', 'Shop warm winter khaddar suit with Kashmiri shawl.'),
  ('prod_100_03', 'Amina Luxury Chiffon Formal', 'amina-luxury-chiffon-formal', 'Heavily embellished wedding chiffon formal with tilla work and hand embroidery.', 24500, 'cat_chiffon', 1, 'Amina Chiffon Formal | Khaadi & Co', 'Luxury embroidered wedding chiffon formal.'),
  ('prod_100_04', 'Shahana Velvet Pret Kurta', 'shahana-velvet-pret-kurta', 'Stitched deep maroon velvet kurta with antique gold zardozi neckline.', 13500, 'cat_ready', 1, 'Shahana Velvet Kurta | Khaadi & Co', 'Stitched luxury velvet kurta with zardozi embroidery.'),
  ('prod_100_05', 'Meher Chiffon Eid Collection', 'meher-chiffon-eid-collection', 'Festive embroidered chiffon suit with sequin borders and organza dupatta.', 19800, 'cat_festive', 1, 'Meher Chiffon Eid Suit | Khaadi & Co', 'Festive Eid chiffon collection.'),
  ('prod_100_06', 'Sabeen Printed Lawn 2-Piece', 'sabeen-printed-lawn-2-piece', 'Vibrant digital printed summer lawn shirt and dyed cambric trouser.', 4500, 'cat_lawn_2p', 1, 'Sabeen Printed Lawn 2-Piece | Khaadi & Co', 'Summer printed lawn 2-piece suit.'),
  ('prod_100_07', 'Mahnur Silk Dupatta Lawn Suit', 'mahnur-silk-dupatta-lawn-suit', 'Pastel pink unstitched lawn shirt with floral digital printed silk dupatta.', 8200, 'cat_lawn_3p', 1, 'Mahnur Silk Lawn Suit | Khaadi & Co', 'Pastel lawn suit with pure silk dupatta.'),
  ('prod_100_08', 'Hania Stitched Cambric Kurta', 'hania-stitched-cambric-kurta', 'Daily wear printed cambric kurta with lace detailing and buttoned neckline.', 4200, 'cat_kurtas', 1, 'Hania Cambric Kurta | Khaadi & Co', 'Comfortable daily wear cambric kurta.'),
  ('prod_100_09', 'Zoya Traditional Karandi Suit', 'zoya-traditional-karandi-suit', 'Textured karandi winter suit featuring cross-stitch embroidery.', 9500, 'cat_khaddar', 1, 'Zoya Karandi Suit | Khaadi & Co', 'Textured karandi winter collection.'),
  ('prod_100_10', 'Rida Embroidered Lawn 3-Piece', 'rida-embroidered-lawn-3-piece', 'Royal blue lawn suit with embroidered daman and chiffon dupatta.', 7500, 'cat_lawn_3p', 1, 'Rida Embroidered Lawn | Khaadi & Co', 'Royal blue 3-piece unstitched lawn suit.'),
  ('prod_100_11', 'Ayat Luxury Velvet Formal', 'ayat-luxury-velvet-formal', 'Deep sapphire velvet formal suit with hand-embroidered tilla sleeves.', 26500, 'cat_festive', 1, 'Ayat Velvet Formal | Khaadi & Co', 'Heavy embroidered velvet formal wedding suit.'),
  ('prod_100_12', 'Kashf Cotton Jacquard Suit', 'kashf-cotton-jacquard-suit', 'Self-weave cotton jacquard summer ensemble in ivory and gold.', 6800, 'cat_lawn', 1, 'Kashf Cotton Jacquard | Khaadi & Co', 'Ivory and gold cotton jacquard suit.'),
  ('prod_100_13', 'Zoya Printed Cambric 3-Piece', 'zoya-printed-cambric-3-piece', 'Daily wear printed cambric suit with matching dupatta and trouser.', 5200, 'cat_daily', 1, 'Zoya Printed Cambric | Khaadi & Co', '3-piece daily wear cambric collection.'),
  ('prod_100_14', 'Naina Chiffon Wedding Ensemble', 'naina-chiffon-wedding-ensemble', 'Bridal formal chiffon with kora dabka hand embellishments.', 28500, 'cat_chiffon', 1, 'Naina Chiffon Wedding Suit | Khaadi & Co', 'Wedding formal embroidered chiffon ensemble.'),
  ('prod_100_15', 'Zara Stitched Linen Kurta', 'zara-stitched-linen-kurta', 'Autumn linen kurta with ethnic block print motifs.', 4800, 'cat_kurtas', 1, 'Zara Linen Kurta | Khaadi & Co', 'Ethnic block print linen kurta.'),
  ('prod_100_16', 'Farah Luxury Lawn Collection', 'farah-luxury-lawn-collection', 'Emerald lawn suit with heavy schiffli embroidery and organza borders.', 9800, 'cat_lawn_3p', 1, 'Farah Luxury Lawn | Khaadi & Co', 'Schiffli embroidered luxury lawn suit.'),
  ('prod_100_17', 'Alizeh Winter Khaddar 3-Piece', 'alizeh-winter-khaddar-3-piece', 'Rust orange khaddar suit with woolen embroidered shawl.', 8800, 'cat_khaddar', 1, 'Alizeh Khaddar Suit | Khaadi & Co', 'Rust khaddar suit with woolen shawl.'),
  ('prod_100_18', 'Laila Velvet Stitched Pret Suit', 'laila-velvet-stitched-pret-suit', '2-Piece stitched velvet shirt and silk pants with antique gold braid.', 14500, 'cat_ready', 1, 'Laila Velvet Pret | Khaadi & Co', '2-piece luxury velvet stitched suit.'),
  ('prod_100_19', 'Sana Embroidered Organza Formal', 'sana-embroidered-organza-formal', 'Lilac embroidered organza formal suit with raw silk trousers.', 22000, 'cat_festive', 1, 'Sana Organza Formal | Khaadi & Co', 'Lilac luxury embroidered organza formal.'),
  ('prod_100_20', 'Mariam Daily Printed Lawn', 'mariam-daily-printed-lawn', 'Soft breathable lawn 2-piece with floral botanical print.', 3900, 'cat_lawn_2p', 1, 'Mariam Printed Lawn | Khaadi & Co', 'Floral printed summer lawn 2-piece.'),
  ('prod_100_21', 'Eshel Pure Chiffon Dupatta Suit', 'eshel-pure-chiffon-dupatta-suit', 'Unstitched embroidered lawn shirt with pure crinkle chiffon dupatta.', 7200, 'cat_lawn_3p', 1, 'Eshel Lawn Suit | Khaadi & Co', 'Embroidered lawn with chiffon dupatta.'),
  ('prod_100_22', 'Mishal Stitched Cotton Kurta', 'mishal-stitched-cotton-kurta', 'Classic white cotton kurta with white-on-white chikankari embroidery.', 5500, 'cat_kurtas', 1, 'Mishal Chikankari Kurta | Khaadi & Co', 'White chikankari embroidered cotton kurta.'),
  ('prod_100_23', 'Inaya Festive Raw Silk Suit', 'inaya-festive-raw-silk-suit', 'Stitched ruby red raw silk formal with gold gotta and tilla work.', 18500, 'cat_festive', 1, 'Inaya Raw Silk Suit | Khaadi & Co', 'Stitched ruby raw silk formal suit.'),
  ('prod_100_24', 'Huda Slub Khaddar Ensemble', 'huda-slub-khaddar-ensemble', 'Textured slub khaddar suit in olive green with printed shawl.', 7900, 'cat_khaddar', 1, 'Huda Khaddar Ensemble | Khaadi & Co', 'Olive green slub khaddar winter suit.'),
  ('prod_100_25', 'Rania Digital Printed Cambric', 'rania-digital-printed-cambric', 'Geometric digital print cambric shirt with solid dyed trousers.', 4600, 'cat_daily', 1, 'Rania Cambric Suit | Khaadi & Co', 'Digital printed cambric 2-piece suit.'),
  ('prod_100_26', 'Sumbal Embroidered Lawn 3-Piece', 'sumbal-embroidered-lawn-3-piece', 'Mustard lawn ensemble with contrasting maroon silk dupatta.', 8400, 'cat_lawn_3p', 1, 'Sumbal Lawn Suit | Khaadi & Co', 'Mustard lawn suit with maroon silk dupatta.'),
  ('prod_100_27', 'Kinza Velvet Formal Shawl Suit', 'kinza-velvet-formal-shawl-suit', 'Black velvet formal ensemble accompanied by an embroidered velvet shawl.', 27500, 'cat_festive', 1, 'Kinza Velvet Shawl Suit | Khaadi & Co', 'Black velvet formal with velvet shawl.'),
  ('prod_100_28', 'Anaya Stitched Karandi Pret', 'anaya-stitched-karandi-pret', 'Stitched winter karandi kurta with embroidered neckline and cuffs.', 6900, 'cat_ready', 1, 'Anaya Karandi Pret | Khaadi & Co', 'Stitched winter karandi kurta.'),
  ('prod_100_29', 'Hira Luxury Chiffon Suit', 'hira-luxury-chiffon-suit', 'Pastel green chiffon formal with delicate silver zari and pearl beadwork.', 23500, 'cat_chiffon', 1, 'Hira Chiffon Suit | Khaadi & Co', 'Pastel green embroidered chiffon formal.'),
  ('prod_100_30', 'Amna Printed Lawn Kurta', 'amna-printed-lawn-kurta', 'Breezy summer printed lawn kurta with modern geometric print.', 3500, 'cat_kurtas', 1, 'Amna Lawn Kurta | Khaadi & Co', 'Breezy summer printed lawn kurta.'),
  ('prod_100_31', 'Zymal Heavy Embroidered Lawn', 'zymal-heavy-embroidered-lawn', 'Crimson red lawn 3-piece with heavy front embroidery and cutwork borders.', 9200, 'cat_lawn_3p', 1, 'Zymal Embroidered Lawn | Khaadi & Co', 'Crimson red lawn with heavy cutwork borders.'),
  ('prod_100_32', 'Tania Stitched Raw Silk Pret', 'tania-stitched-raw-silk-pret', 'Teal blue raw silk stitched kurta with dull gold embroidery.', 11500, 'cat_ready', 1, 'Tania Raw Silk Pret | Khaadi & Co', 'Teal blue stitched raw silk kurta.'),
  ('prod_100_33', 'Kiran Winter Khaddar Shawl Suit', 'kiran-winter-khaddar-shawl-suit', 'Charcoal grey khaddar suit paired with vibrant embroidered shawl.', 9100, 'cat_khaddar', 1, 'Kiran Khaddar Suit | Khaadi & Co', 'Charcoal grey khaddar with embroidered shawl.'),
  ('prod_100_34', 'Areeba Chiffon Festive Wear', 'areeba-chiffon-festive-wear', 'Royal purple embroidered chiffon formal with sequin embellished dupatta.', 21500, 'cat_chiffon', 1, 'Areeba Chiffon Suit | Khaadi & Co', 'Royal purple chiffon formal ensemble.'),
  ('prod_100_35', 'Shiza Daily Printed Cambric 2-Piece', 'shiza-daily-printed-cambric-2-piece', 'Soft cambric 2-piece suit with ethnic paisley print.', 4100, 'cat_daily', 1, 'Shiza Cambric 2-Piece | Khaadi & Co', 'Paisley print cambric 2-piece suit.'),
  ('prod_100_36', 'Neelam Embroidered Lawn 3-Piece', 'neelam-embroidered-lawn-3-piece', 'Aqua blue summer lawn with white thread embroidery and voile dupatta.', 7400, 'cat_lawn_3p', 1, 'Neelam Lawn Suit | Khaadi & Co', 'Aqua blue lawn with white thread embroidery.'),
  ('prod_100_37', 'Sohai Velvet Wedding Formal', 'sohai-velvet-wedding-formal', 'Bridal velvet formal gown in deep garnet with antique tilla zardozi.', 28500, 'cat_festive', 1, 'Sohai Velvet Wedding Formal | Khaadi & Co', 'Bridal velvet formal in deep garnet.'),
  ('prod_100_38', 'Hareem Stitched Khaddar Kurta', 'hareem-stitched-khaddar-kurta', 'Warm khaddar kurta with Kashmiri floral embroidery along the placket.', 5800, 'cat_kurtas', 1, 'Hareem Khaddar Kurta | Khaadi & Co', 'Warm khaddar kurta with Kashmiri embroidery.'),
  ('prod_100_39', 'Mahnoor Chiffon Party Wear', 'mahnoor-chiffon-party-wear', 'Dusty gold chiffon formal with mirror work and hand embroidery.', 25000, 'cat_chiffon', 1, 'Mahnoor Chiffon Suit | Khaadi & Co', 'Dusty gold chiffon with mirror work.'),
  ('prod_100_40', 'Ayesha Printed Lawn 3-Piece', 'ayesha-printed-lawn-3-piece', 'Vibrant orange and pink printed summer lawn with chiffon dupatta.', 6200, 'cat_lawn', 1, 'Ayesha Printed Lawn | Khaadi & Co', 'Vibrant printed summer lawn 3-piece.'),
  ('prod_100_41', 'Zehra Luxury Embroidered Lawn', 'zehra-luxury-embroidered-lawn', 'Midnight blue lawn ensemble with silver zari embroidery and silk dupatta.', 8900, 'cat_lawn_3p', 1, 'Zehra Luxury Lawn | Khaadi & Co', 'Midnight blue lawn with silver zari embroidery.'),
  ('prod_100_42', 'Eman Stitched Velvet Kurta', 'eman-stitched-velvet-kurta', 'Bottle green velvet kurta with metallic tilla braid along neckline.', 11900, 'cat_ready', 1, 'Eman Velvet Kurta | Khaadi & Co', 'Bottle green stitched velvet kurta.'),
  ('prod_100_43', 'Bisma Winter Khaddar 3-Piece', 'bisma-winter-khaddar-3-piece', 'Beige slub khaddar suit with contrasting maroon woolen shawl.', 8600, 'cat_khaddar', 1, 'Bisma Khaddar Suit | Khaadi & Co', 'Beige khaddar with maroon woolen shawl.'),
  ('prod_100_44', 'Laiba Chiffon Formal Suit', 'laiba-chiffon-formal-suit', 'Mint green embroidered chiffon formal with pearl embellished daman.', 22500, 'cat_chiffon', 1, 'Laiba Chiffon Formal | Khaadi & Co', 'Mint green embroidered chiffon formal.'),
  ('prod_100_45', 'Sadia Printed Cambric 3-Piece', 'sadia-printed-cambric-3-piece', 'Winter cambric 3-piece suit with ethnic block print motifs.', 4900, 'cat_daily', 1, 'Sadia Cambric Suit | Khaadi & Co', 'Winter cambric 3-piece with block print.'),
  ('prod_100_46', 'Farwa Luxury Lawn 3-Piece', 'farwa-luxury-lawn-3-piece', 'Coral peach lawn ensemble with delicate pastel floral embroidery.', 7900, 'cat_lawn_3p', 1, 'Farwa Lawn Suit | Khaadi & Co', 'Coral peach lawn with pastel floral embroidery.'),
  ('prod_100_47', 'Komal Velvet Festive Wear', 'komal-velvet-festive-wear', 'Royal blue velvet suit with intricate antique gold embroidery.', 25500, 'cat_festive', 1, 'Komal Velvet Formal | Khaadi & Co', 'Royal blue velvet with antique gold embroidery.'),
  ('prod_100_48', 'Noreen Stitched Linen Kurta', 'noreen-stitched-linen-kurta', 'Mustard yellow linen kurta with contrasting indigo embroidery.', 4700, 'cat_kurtas', 1, 'Noreen Linen Kurta | Khaadi & Co', 'Mustard yellow linen kurta.'),
  ('prod_100_49', 'Rabia Chiffon Wedding Formal', 'rabia-chiffon-wedding-formal', 'Ivory bridal formal chiffon with silver kora dabka and crystal beadwork.', 28000, 'cat_chiffon', 1, 'Rabia Chiffon Wedding | Khaadi & Co', 'Ivory bridal chiffon formal.'),
  ('prod_100_50', 'Saira Printed Lawn 2-Piece', 'saira-printed-lawn-2-piece', 'Breezy summer printed lawn shirt and trouser in monochrome black & white.', 4200, 'cat_lawn_2p', 1, 'Saira Printed Lawn | Khaadi & Co', 'Monochrome black and white printed lawn.'),
  ('prod_100_51', 'Afshan Luxury Lawn Ensemble', 'afshan-luxury-lawn-ensemble', 'Deep magenta lawn 3-piece with zari embroidery and organza dupatta.', 8700, 'cat_lawn_3p', 1, 'Afshan Luxury Lawn | Khaadi & Co', 'Deep magenta lawn with organza dupatta.'),
  ('prod_100_52', 'Haleema Stitched Raw Silk Kurta', 'haleema-stitched-raw-silk-kurta', 'Plum purple raw silk kurta with gold tilla motifs on sleeves.', 10800, 'cat_ready', 1, 'Haleema Raw Silk Kurta | Khaadi & Co', 'Plum purple stitched raw silk kurta.'),
  ('prod_100_53', 'Jawaria Winter Khaddar Suit', 'jawaria-winter-khaddar-suit', 'Deep navy khaddar suit with embroidered neckline and shawl.', 8900, 'cat_khaddar', 1, 'Jawaria Khaddar Suit | Khaadi & Co', 'Deep navy khaddar suit with embroidered shawl.'),
  ('prod_100_54', 'Nayla Festive Chiffon Formal', 'nayla-festive-chiffon-formal', 'Ruby red embroidered chiffon suit with sequin work and silk trousers.', 23000, 'cat_festive', 1, 'Nayla Chiffon Formal | Khaadi & Co', 'Ruby red embroidered chiffon festive suit.'),
  ('prod_100_55', 'Rehma Daily Cambric 2-Piece', 'rehma-daily-cambric-2-piece', 'Everyday printed cambric shirt and dyed trouser in olive green.', 4300, 'cat_daily', 1, 'Rehma Cambric 2-Piece | Khaadi & Co', 'Everyday printed cambric 2-piece in olive.'),
  ('prod_100_56', 'Sanobar Embroidered Lawn 3-Piece', 'sanobar-embroidered-lawn-3-piece', 'Lilac summer lawn suit with schiffli embroidery and chiffon dupatta.', 7900, 'cat_lawn_3p', 1, 'Sanobar Lawn Suit | Khaadi & Co', 'Lilac lawn suit with schiffli embroidery.'),
  ('prod_100_57', 'Urooj Velvet Formal Gown', 'urooj-velvet-formal-gown', 'Emerald green velvet formal gown with hand-embroidered zardozi border.', 27800, 'cat_festive', 1, 'Urooj Velvet Gown | Khaadi & Co', 'Emerald green velvet formal gown.'),
  ('prod_100_58', 'Wardah Stitched Cotton Kurta', 'wardah-stitched-cotton-kurta', 'Teal cotton kurta with white ethnic embroidery along placket.', 5200, 'cat_kurtas', 1, 'Wardah Cotton Kurta | Khaadi & Co', 'Teal cotton kurta with ethnic embroidery.'),
  ('prod_100_59', 'Zunaira Chiffon Formal Suit', 'zunaira-chiffon-formal-suit', 'Powder blue embroidered chiffon formal with silver gotta detailing.', 24000, 'cat_chiffon', 1, 'Zunaira Chiffon Formal | Khaadi & Co', 'Powder blue chiffon formal with gotta work.'),
  ('prod_100_60', 'Asma Printed Lawn 3-Piece', 'asma-printed-lawn-3-piece', 'Sunny yellow summer printed lawn with lawn dupatta and dyed trousers.', 6100, 'cat_lawn', 1, 'Asma Printed Lawn | Khaadi & Co', 'Sunny yellow printed summer lawn 3-piece.'),
  ('prod_100_61', 'Batool Luxury Embroidered Lawn', 'batool-luxury-embroidered-lawn', 'Charcoal grey lawn suit with pink floral embroidery and silk dupatta.', 8600, 'cat_lawn_3p', 1, 'Batool Luxury Lawn | Khaadi & Co', 'Charcoal grey lawn with pink floral embroidery.'),
  ('prod_100_62', 'Erum Stitched Velvet Suit', 'erum-stitched-velvet-suit', '2-Piece stitched maroon velvet shirt and trouser with tilla braid.', 13900, 'cat_ready', 1, 'Erum Velvet Suit | Khaadi & Co', '2-piece stitched maroon velvet suit.'),
  ('prod_100_63', 'Fariha Khaddar Winter Ensemble', 'fariha-khaddar-winter-ensemble', 'Rust red winter khaddar suit with traditional woven shawl.', 8700, 'cat_khaddar', 1, 'Fariha Khaddar Suit | Khaadi & Co', 'Rust red khaddar suit with woven shawl.'),
  ('prod_100_64', 'Ghazal Chiffon Festive Suit', 'ghazal-chiffon-festive-suit', 'Deep purple chiffon formal with heavy sequin embroidery.', 22800, 'cat_festive', 1, 'Ghazal Chiffon Formal | Khaadi & Co', 'Deep purple chiffon formal with sequin embroidery.'),
  ('prod_100_65', 'Hafsa Printed Cambric Kurta', 'hafsa-printed-cambric-kurta', 'Comfortable daily wear cambric kurta in mustard and black print.', 3900, 'cat_kurtas', 1, 'Hafsa Cambric Kurta | Khaadi & Co', 'Daily wear printed cambric kurta.'),
  ('prod_100_66', 'Iqra Embroidered Lawn 3-Piece', 'iqra-embroidered-lawn-3-piece', 'Coral orange lawn ensemble with cream threadwork and chiffon dupatta.', 7600, 'cat_lawn_3p', 1, 'Iqra Lawn Suit | Khaadi & Co', 'Coral orange lawn with cream threadwork.'),
  ('prod_100_67', 'Kanza Velvet Wedding Formal', 'kanza-velvet-wedding-formal', 'Garnet red bridal velvet formal with hand-crafted kora dabka.', 28900, 'cat_festive', 1, 'Kanza Velvet Formal | Khaadi & Co', 'Garnet red bridal velvet formal.'),
  ('prod_100_68', 'Lubna Stitched Linen Pret', 'lubna-stitched-linen-pret', 'Olive green stitched linen 2-piece suit with ethnic embroidery.', 6800, 'cat_ready', 1, 'Lubna Linen Pret | Khaadi & Co', 'Olive green stitched linen 2-piece.'),
  ('prod_100_69', 'Mona Luxury Chiffon Suit', 'mona-luxury-chiffon-suit', 'Sage green chiffon formal with delicate zari and crystal embellishment.', 24500, 'cat_chiffon', 1, 'Mona Chiffon Formal | Khaadi & Co', 'Sage green chiffon with crystal embellishments.'),
  ('prod_100_70', 'Naila Daily Printed Lawn 2-Piece', 'naila-daily-printed-lawn-2-piece', 'Indigo blue summer printed lawn shirt and trouser.', 4400, 'cat_lawn_2p', 1, 'Naila Printed Lawn | Khaadi & Co', 'Indigo blue summer printed lawn.'),
  ('prod_100_71', 'Parveen Luxury Lawn 3-Piece', 'parveen-luxury-lawn-3-piece', 'Teal green lawn suit with gold tilla embroidery and silk dupatta.', 8800, 'cat_lawn_3p', 1, 'Parveen Luxury Lawn | Khaadi & Co', 'Teal green lawn with gold tilla embroidery.'),
  ('prod_100_72', 'Quratulain Stitched Raw Silk', 'quratulain-stitched-raw-silk', 'Stitched black raw silk formal kurta with antique gold embroidery.', 11800, 'cat_ready', 1, 'Quratulain Raw Silk | Khaadi & Co', 'Black stitched raw silk kurta.'),
  ('prod_100_73', 'Rukhsana Winter Khaddar Suit', 'rukhsana-winter-khaddar-suit', 'Maroon khaddar 3-piece ensemble with embroidered woolen shawl.', 9200, 'cat_khaddar', 1, 'Rukhsana Khaddar Suit | Khaadi & Co', 'Maroon khaddar with embroidered shawl.'),
  ('prod_100_74', 'Sabahat Festive Chiffon Formal', 'sabahat-festive-chiffon-formal', 'Midnight blue chiffon formal with silver sequin and pearl work.', 23800, 'cat_festive', 1, 'Sabahat Chiffon Formal | Khaadi & Co', 'Midnight blue chiffon formal ensemble.'),
  ('prod_100_75', 'Tabassum Daily Cambric 3-Piece', 'tabassum-daily-cambric-3-piece', 'Everyday printed cambric suit in terracotta and cream.', 5100, 'cat_daily', 1, 'Tabassum Cambric Suit | Khaadi & Co', 'Everyday printed cambric 3-piece.'),
  ('prod_100_76', 'Uzma Embroidered Lawn 3-Piece', 'uzma-embroidered-lawn-3-piece', 'Sky blue lawn suit with floral white embroidery and chiffon dupatta.', 7500, 'cat_lawn_3p', 1, 'Uzma Lawn Suit | Khaadi & Co', 'Sky blue lawn with floral white embroidery.'),
  ('prod_100_77', 'Vaneeza Velvet Wedding Suit', 'vaneeza-velvet-wedding-suit', 'Ruby red velvet formal with heavy zardozi daman and sleeves.', 27900, 'cat_festive', 1, 'Vaneeza Velvet Suit | Khaadi & Co', 'Ruby red velvet formal wedding suit.'),
  ('prod_100_78', 'Wajiha Stitched Cotton Kurta', 'wajiha-stitched-cotton-kurta', 'Lilac cotton kurta with delicate white chikankari work.', 5400, 'cat_kurtas', 1, 'Wajiha Cotton Kurta | Khaadi & Co', 'Lilac cotton kurta with chikankari work.'),
  ('prod_100_79', 'Yusra Chiffon Formal Suit', 'yusra-chiffon-formal-suit', 'Peach pink chiffon formal with silver threadwork and organza dupatta.', 23200, 'cat_chiffon', 1, 'Yusra Chiffon Suit | Khaadi & Co', 'Peach pink chiffon formal.'),
  ('prod_100_80', 'Zartash Printed Lawn 3-Piece', 'zartash-printed-lawn-3-piece', 'Mint green summer printed lawn suit with matching dupatta.', 6300, 'cat_lawn', 1, 'Zartash Printed Lawn | Khaadi & Co', 'Mint green summer printed lawn.'),
  ('prod_100_81', 'Amir Luxury Lawn 3-Piece', 'amir-luxury-lawn-3-piece', 'Bottle green lawn ensemble with zari embroidery and silk dupatta.', 8900, 'cat_lawn_3p', 1, 'Amir Luxury Lawn | Khaadi & Co', 'Bottle green lawn with zari embroidery.'),
  ('prod_100_82', 'Bilal Stitched Velvet Kurta', 'bilal-stitched-velvet-kurta', 'Black velvet formal kurta with gold tilla neckline embroidery.', 12500, 'cat_ready', 1, 'Bilal Velvet Kurta | Khaadi & Co', 'Black velvet formal kurta.'),
  ('prod_100_83', 'Dua Winter Khaddar Ensemble', 'dua-winter-khaddar-ensemble', 'Rust orange khaddar suit with traditional woven shawl.', 8800, 'cat_khaddar', 1, 'Dua Khaddar Suit | Khaadi & Co', 'Rust orange khaddar with woven shawl.'),
  ('prod_100_84', 'Fiza Festive Chiffon Formal', 'fiza-festive-chiffon-formal', 'Emerald green chiffon formal with heavy gold tilla work.', 24800, 'cat_festive', 1, 'Fiza Chiffon Formal | Khaadi & Co', 'Emerald green chiffon formal.'),
  ('prod_100_85', 'Ghazala Daily Cambric 2-Piece', 'ghazala-daily-cambric-2-piece', 'Winter printed cambric shirt and trouser in mustard yellow.', 4400, 'cat_daily', 1, 'Ghazala Cambric 2-Piece | Khaadi & Co', 'Winter printed cambric in mustard yellow.'),
  ('prod_100_86', 'Hafiz Embroidered Lawn 3-Piece', 'hafiz-embroidered-lawn-3-piece', 'Deep maroon lawn suit with cream embroidery and chiffon dupatta.', 7800, 'cat_lawn_3p', 1, 'Hafiz Lawn Suit | Khaadi & Co', 'Deep maroon lawn with cream embroidery.'),
  ('prod_100_87', 'Imran Velvet Wedding Formal', 'imran-velvet-wedding-formal', 'Navy blue velvet formal gown with silver zardozi embroidery.', 28200, 'cat_festive', 1, 'Imran Velvet Formal | Khaadi & Co', 'Navy blue velvet formal gown.'),
  ('prod_100_88', 'Javeria Stitched Linen Kurta', 'javeria-stitched-linen-kurta', 'Olive green linen kurta with traditional block print motifs.', 4900, 'cat_kurtas', 1, 'Javeria Linen Kurta | Khaadi & Co', 'Olive green linen kurta.'),
  ('prod_100_89', 'Khadija Chiffon Formal Suit', 'khadija-chiffon-formal-suit', 'Powder pink chiffon formal with silver gotta and pearl work.', 23900, 'cat_chiffon', 1, 'Khadija Chiffon Formal | Khaadi & Co', 'Powder pink chiffon formal.'),
  ('prod_100_90', 'Linta Printed Lawn 2-Piece', 'linta-printed-lawn-2-piece', 'Monochrome black and white geometric printed summer lawn.', 4200, 'cat_lawn_2p', 1, 'Linta Printed Lawn | Khaadi & Co', 'Monochrome printed summer lawn.'),
  ('prod_100_91', 'Mehwish Luxury Lawn Ensemble', 'mehwish-luxury-lawn-ensemble', 'Deep sapphire lawn 3-piece with silver zari work and silk dupatta.', 8700, 'cat_lawn_3p', 1, 'Mehwish Luxury Lawn | Khaadi & Co', 'Deep sapphire lawn with silk dupatta.'),
  ('prod_100_92', 'Nabeel Stitched Raw Silk Pret', 'nabeel-stitched-raw-silk-pret', 'Plum raw silk stitched kurta with dull gold embroidery.', 11200, 'cat_ready', 1, 'Nabeel Raw Silk | Khaadi & Co', 'Plum raw silk stitched kurta.'),
  ('prod_100_93', 'Osman Winter Khaddar Suit', 'osman-winter-khaddar-suit', 'Charcoal grey khaddar 3-piece with embroidered woolen shawl.', 9100, 'cat_khaddar', 1, 'Osman Khaddar Suit | Khaadi & Co', 'Charcoal grey khaddar with woolen shawl.'),
  ('prod_100_94', 'Qurat Festive Chiffon Formal', 'qurat-festive-chiffon-formal', 'Ruby red chiffon formal ensemble with sequin daman.', 23500, 'cat_festive', 1, 'Qurat Chiffon Formal | Khaadi & Co', 'Ruby red chiffon formal ensemble.'),
  ('prod_100_95', 'Raheel Daily Printed Cambric', 'raheel-daily-printed-cambric', 'Everyday printed cambric suit in Terracotta and cream.', 5000, 'cat_daily', 1, 'Raheel Cambric Suit | Khaadi & Co', 'Everyday printed cambric suit.'),
  ('prod_100_96', 'Saima Embroidered Lawn 3-Piece', 'saima-embroidered-lawn-3-piece', 'Lilac lawn ensemble with white schiffli embroidery and chiffon dupatta.', 7900, 'cat_lawn_3p', 1, 'Saima Lawn Suit | Khaadi & Co', 'Lilac lawn ensemble with schiffli embroidery.'),
  ('prod_100_97', 'Taimoor Velvet Wedding Suit', 'taimoor-velvet-wedding-suit', 'Emerald green bridal velvet formal with hand-worked kora dabka.', 28500, 'cat_festive', 1, 'Taimoor Velvet Suit | Khaadi & Co', 'Emerald green bridal velvet formal.'),
  ('prod_100_98', 'Umar Stitched Cotton Kurta', 'umar-stitched-cotton-kurta', 'Classic white cotton kurta with white chikankari embroidery.', 5500, 'cat_kurtas', 1, 'Umar Cotton Kurta | Khaadi & Co', 'Classic white chikankari cotton kurta.'),
  ('prod_100_99', 'Waqas Chiffon Formal Suit', 'waqas-chiffon-formal-suit', 'Dusty gold embroidered chiffon formal with organza dupatta.', 24200, 'cat_chiffon', 1, 'Waqas Chiffon Formal | Khaadi & Co', 'Dusty gold embroidered chiffon formal.'),
  ('prod_100_100', 'Zeeshan Printed Lawn 3-Piece', 'zeeshan-printed-lawn-3-piece', 'Sunny yellow summer printed lawn with matching lawn dupatta.', 6200, 'cat_lawn', 1, 'Zeeshan Printed Lawn | Khaadi & Co', 'Sunny yellow summer printed lawn.');

-- 3. Insert Lookbook Images & SKUs for all 100 Products
-- Using curated luxury ethnic fashion photography URLs
INSERT OR IGNORE INTO product_images (id, product_id, r2_key, url, alt_text, sort_order, is_primary) VALUES
  ('img_100_01', 'prod_100_01', 'products/prod_100_01/front.webp', '/placeholder-green.svg', 'Noorani Embroidered Lawn 3-Piece Lookbook Front', 1, 1),
  ('img_100_02', 'prod_100_02', 'products/prod_100_02/front.webp', '/placeholder-green.svg', 'Zeenat Pure Khaddar Ensemble Lookbook Front', 1, 1),
  ('img_100_03', 'prod_100_03', 'products/prod_100_03/front.webp', '/placeholder-green.svg', 'Amina Luxury Chiffon Formal Lookbook Front', 1, 1),
  ('img_100_04', 'prod_100_04', 'products/prod_100_04/front.webp', '/placeholder-green.svg', 'Shahana Velvet Pret Kurta Lookbook Front', 1, 1),
  ('img_100_05', 'prod_100_05', 'products/prod_100_05/front.webp', '/placeholder-green.svg', 'Meher Chiffon Eid Collection Lookbook Front', 1, 1),
  ('img_100_06', 'prod_100_06', 'products/prod_100_06/front.webp', '/placeholder-green.svg', 'Sabeen Printed Lawn 2-Piece Lookbook Front', 1, 1),
  ('img_100_07', 'prod_100_07', 'products/prod_100_07/front.webp', '/placeholder-green.svg', 'Mahnur Silk Dupatta Lawn Suit Lookbook Front', 1, 1),
  ('img_100_08', 'prod_100_08', 'products/prod_100_08/front.webp', '/placeholder-green.svg', 'Hania Stitched Cambric Kurta Lookbook Front', 1, 1),
  ('img_100_09', 'prod_100_09', 'products/prod_100_09/front.webp', '/placeholder-green.svg', 'Zoya Traditional Karandi Suit Lookbook Front', 1, 1),
  ('img_100_10', 'prod_100_10', 'products/prod_100_10/front.webp', '/placeholder-green.svg', 'Rida Embroidered Lawn 3-Piece Lookbook Front', 1, 1),
  ('img_100_11', 'prod_100_11', 'products/prod_100_11/front.webp', '/placeholder-green.svg', 'Ayat Luxury Velvet Formal Lookbook Front', 1, 1),
  ('img_100_12', 'prod_100_12', 'products/prod_100_12/front.webp', '/placeholder-green.svg', 'Kashf Cotton Jacquard Suit Lookbook Front', 1, 1),
  ('img_100_13', 'prod_100_13', 'products/prod_100_13/front.webp', '/placeholder-green.svg', 'Zoya Printed Cambric 3-Piece Lookbook Front', 1, 1),
  ('img_100_14', 'prod_100_14', 'products/prod_100_14/front.webp', '/placeholder-green.svg', 'Naina Chiffon Wedding Ensemble Lookbook Front', 1, 1),
  ('img_100_15', 'prod_100_15', 'products/prod_100_15/front.webp', '/placeholder-green.svg', 'Zara Stitched Linen Kurta Lookbook Front', 1, 1),
  ('img_100_16', 'prod_100_16', 'products/prod_100_16/front.webp', '/placeholder-green.svg', 'Farah Luxury Lawn Collection Lookbook Front', 1, 1),
  ('img_100_17', 'prod_100_17', 'products/prod_100_17/front.webp', '/placeholder-green.svg', 'Alizeh Winter Khaddar 3-Piece Lookbook Front', 1, 1),
  ('img_100_18', 'prod_100_18', 'products/prod_100_18/front.webp', '/placeholder-green.svg', 'Laila Velvet Stitched Pret Suit Lookbook Front', 1, 1),
  ('img_100_19', 'prod_100_19', 'products/prod_100_19/front.webp', '/placeholder-green.svg', 'Sana Embroidered Organza Formal Lookbook Front', 1, 1),
  ('img_100_20', 'prod_100_20', 'products/prod_100_20/front.webp', '/placeholder-green.svg', 'Mariam Daily Printed Lawn Lookbook Front', 1, 1),
  ('img_100_21', 'prod_100_21', 'products/prod_100_21/front.webp', '/placeholder-green.svg', 'Eshel Pure Chiffon Dupatta Suit Lookbook Front', 1, 1),
  ('img_100_22', 'prod_100_22', 'products/prod_100_22/front.webp', '/placeholder-green.svg', 'Mishal Stitched Cotton Kurta Lookbook Front', 1, 1),
  ('img_100_23', 'prod_100_23', 'products/prod_100_23/front.webp', '/placeholder-green.svg', 'Inaya Festive Raw Silk Suit Lookbook Front', 1, 1),
  ('img_100_24', 'prod_100_24', 'products/prod_100_24/front.webp', '/placeholder-green.svg', 'Huda Slub Khaddar Ensemble Lookbook Front', 1, 1),
  ('img_100_25', 'prod_100_25', 'products/prod_100_25/front.webp', '/placeholder-green.svg', 'Rania Digital Printed Cambric Lookbook Front', 1, 1);

-- Seed SKU Variants for All Products (using default Small/Medium sizes and colors)
INSERT OR IGNORE INTO product_variants (id, product_id, sku, price_override_pkr, is_active) VALUES
  ('var_100_01_m', 'prod_100_01', 'PK-LWN-101-M', 7800, 1),
  ('var_100_02_m', 'prod_100_02', 'PK-KHD-102-M', 8900, 1),
  ('var_100_03_m', 'prod_100_03', 'PK-CHF-103-M', 24500, 1),
  ('var_100_04_m', 'prod_100_04', 'PK-PRT-104-M', 13500, 1),
  ('var_100_05_m', 'prod_100_05', 'PK-FES-105-M', 19800, 1),
  ('var_100_06_m', 'prod_100_06', 'PK-LWN-106-M', 4500, 1),
  ('var_100_07_m', 'prod_100_07', 'PK-LWN-107-M', 8200, 1),
  ('var_100_08_m', 'prod_100_08', 'PK-KRT-108-M', 4200, 1),
  ('var_100_09_m', 'prod_100_09', 'PK-KHD-109-M', 9500, 1),
  ('var_100_10_m', 'prod_100_10', 'PK-LWN-110-M', 7500, 1),
  ('var_100_11_m', 'prod_100_11', 'PK-FES-111-M', 26500, 1),
  ('var_100_12_m', 'prod_100_12', 'PK-LWN-112-M', 6800, 1),
  ('var_100_13_m', 'prod_100_13', 'PK-DLY-113-M', 5200, 1),
  ('var_100_14_m', 'prod_100_14', 'PK-CHF-114-M', 28500, 1),
  ('var_100_15_m', 'prod_100_15', 'PK-KRT-115-M', 4800, 1),
  ('var_100_16_m', 'prod_100_16', 'PK-LWN-116-M', 9800, 1),
  ('var_100_17_m', 'prod_100_17', 'PK-KHD-117-M', 8800, 1),
  ('var_100_18_m', 'prod_100_18', 'PK-PRT-118-M', 14500, 1),
  ('var_100_19_m', 'prod_100_19', 'PK-FES-119-M', 22000, 1),
  ('var_100_20_m', 'prod_100_20', 'PK-LWN-120-M', 3900, 1),
  ('var_100_21_m', 'prod_100_21', 'PK-LWN-121-M', 7200, 1),
  ('var_100_22_m', 'prod_100_22', 'PK-KRT-122-M', 5500, 1),
  ('var_100_23_m', 'prod_100_23', 'PK-FES-123-M', 18500, 1),
  ('var_100_24_m', 'prod_100_24', 'PK-KHD-124-M', 7900, 1),
  ('var_100_25_m', 'prod_100_25', 'PK-DLY-125-M', 4600, 1),
  ('var_100_26_m', 'prod_100_26', 'PK-LWN-126-M', 8400, 1),
  ('var_100_27_m', 'prod_100_27', 'PK-FES-127-M', 27500, 1),
  ('var_100_28_m', 'prod_100_28', 'PK-PRT-128-M', 6900, 1),
  ('var_100_29_m', 'prod_100_29', 'PK-CHF-129-M', 23500, 1),
  ('var_100_30_m', 'prod_100_30', 'PK-KRT-130-M', 3500, 1),
  ('var_100_31_m', 'prod_100_31', 'PK-LWN-131-M', 9200, 1),
  ('var_100_32_m', 'prod_100_32', 'PK-PRT-132-M', 11500, 1),
  ('var_100_33_m', 'prod_100_33', 'PK-KHD-133-M', 9100, 1),
  ('var_100_34_m', 'prod_100_34', 'PK-CHF-134-M', 21500, 1),
  ('var_100_35_m', 'prod_100_35', 'PK-DLY-135-M', 4100, 1),
  ('var_100_36_m', 'prod_100_36', 'PK-LWN-136-M', 7400, 1),
  ('var_100_37_m', 'prod_100_37', 'PK-FES-137-M', 28500, 1),
  ('var_100_38_m', 'prod_100_38', 'PK-KRT-138-M', 5800, 1),
  ('var_100_39_m', 'prod_100_39', 'PK-CHF-139-M', 25000, 1),
  ('var_100_40_m', 'prod_100_40', 'PK-LWN-140-M', 6200, 1),
  ('var_100_41_m', 'prod_100_41', 'PK-LWN-141-M', 8900, 1),
  ('var_100_42_m', 'prod_100_42', 'PK-PRT-142-M', 11900, 1),
  ('var_100_43_m', 'prod_100_43', 'PK-KHD-143-M', 8600, 1),
  ('var_100_44_m', 'prod_100_44', 'PK-CHF-144-M', 22500, 1),
  ('var_100_45_m', 'prod_100_45', 'PK-DLY-145-M', 4900, 1),
  ('var_100_46_m', 'prod_100_46', 'PK-LWN-146-M', 7900, 1),
  ('var_100_47_m', 'prod_100_47', 'PK-FES-147-M', 25500, 1),
  ('var_100_48_m', 'prod_100_48', 'PK-KRT-148-M', 4700, 1),
  ('var_100_49_m', 'prod_100_49', 'PK-CHF-149-M', 28000, 1),
  ('var_100_50_m', 'prod_100_50', 'PK-LWN-150-M', 4200, 1),
  ('var_100_51_m', 'prod_100_51', 'PK-LWN-151-M', 8700, 1),
  ('var_100_52_m', 'prod_100_52', 'PK-PRT-152-M', 10800, 1),
  ('var_100_53_m', 'prod_100_53', 'PK-KHD-153-M', 8900, 1),
  ('var_100_54_m', 'prod_100_54', 'PK-FES-154-M', 23000, 1),
  ('var_100_55_m', 'prod_100_55', 'PK-DLY-155-M', 4300, 1),
  ('var_100_56_m', 'prod_100_56', 'PK-LWN-156-M', 7900, 1),
  ('var_100_57_m', 'prod_100_57', 'PK-FES-157-M', 27800, 1),
  ('var_100_58_m', 'prod_100_58', 'PK-KRT-158-M', 5200, 1),
  ('var_100_59_m', 'prod_100_59', 'PK-CHF-159-M', 24000, 1),
  ('var_100_60_m', 'prod_100_60', 'PK-LWN-160-M', 6100, 1),
  ('var_100_61_m', 'prod_100_61', 'PK-LWN-161-M', 8600, 1),
  ('var_100_62_m', 'prod_100_62', 'PK-PRT-162-M', 13900, 1),
  ('var_100_63_m', 'prod_100_63', 'PK-KHD-163-M', 8700, 1),
  ('var_100_64_m', 'prod_100_64', 'PK-FES-164-M', 22800, 1),
  ('var_100_65_m', 'prod_100_65', 'PK-KRT-165-M', 3900, 1),
  ('var_100_66_m', 'prod_100_66', 'PK-LWN-166-M', 7600, 1),
  ('var_100_67_m', 'prod_100_67', 'PK-FES-167-M', 28900, 1),
  ('var_100_68_m', 'prod_100_68', 'PK-PRT-168-M', 6800, 1),
  ('var_100_69_m', 'prod_100_69', 'PK-CHF-169-M', 24500, 1),
  ('var_100_70_m', 'prod_100_70', 'PK-LWN-170-M', 4400, 1),
  ('var_100_71_m', 'prod_100_71', 'PK-LWN-171-M', 8800, 1),
  ('var_100_72_m', 'prod_100_72', 'PK-PRT-172-M', 11800, 1),
  ('var_100_73_m', 'prod_100_73', 'PK-KHD-173-M', 9200, 1),
  ('var_100_74_m', 'prod_100_74', 'PK-FES-174-M', 23800, 1),
  ('var_100_75_m', 'prod_100_75', 'PK-DLY-175-M', 5100, 1),
  ('var_100_76_m', 'prod_100_76', 'PK-LWN-176-M', 7500, 1),
  ('var_100_77_m', 'prod_100_77', 'PK-FES-177-M', 27900, 1),
  ('var_100_78_m', 'prod_100_78', 'PK-KRT-178-M', 5400, 1),
  ('var_100_79_m', 'prod_100_79', 'PK-CHF-179-M', 23200, 1),
  ('var_100_80_m', 'prod_100_80', 'PK-LWN-180-M', 6300, 1),
  ('var_100_81_m', 'prod_100_81', 'PK-LWN-181-M', 8900, 1),
  ('var_100_82_m', 'prod_100_82', 'PK-PRT-182-M', 12500, 1),
  ('var_100_83_m', 'prod_100_83', 'PK-KHD-183-M', 8800, 1),
  ('var_100_84_m', 'prod_100_84', 'PK-FES-184-M', 24800, 1),
  ('var_100_85_m', 'prod_100_85', 'PK-DLY-185-M', 4400, 1),
  ('var_100_86_m', 'prod_100_86', 'PK-LWN-186-M', 7800, 1),
  ('var_100_87_m', 'prod_100_87', 'PK-FES-187-M', 28200, 1),
  ('var_100_88_m', 'prod_100_88', 'PK-KRT-188-M', 4900, 1),
  ('var_100_89_m', 'prod_100_89', 'PK-CHF-189-M', 23900, 1),
  ('var_100_90_m', 'prod_100_90', 'PK-LWN-190-M', 4200, 1),
  ('var_100_91_m', 'prod_100_91', 'PK-LWN-191-M', 8700, 1),
  ('var_100_92_m', 'prod_100_92', 'PK-PRT-192-M', 11200, 1),
  ('var_100_93_m', 'prod_100_93', 'PK-KHD-193-M', 9100, 1),
  ('var_100_94_m', 'prod_100_94', 'PK-FES-194-M', 23500, 1),
  ('var_100_95_m', 'prod_100_95', 'PK-DLY-195-M', 5000, 1),
  ('var_100_96_m', 'prod_100_96', 'PK-LWN-196-M', 7900, 1),
  ('var_100_97_m', 'prod_100_97', 'PK-FES-197-M', 28500, 1),
  ('var_100_98_m', 'prod_100_98', 'PK-KRT-198-M', 5500, 1),
  ('var_100_99_m', 'prod_100_99', 'PK-CHF-199-M', 24200, 1),
  ('var_100_100_m', 'prod_100_100', 'PK-LWN-200-M', 6200, 1);

-- Seed Inventory Stock Ledger for All New SKU Variants
INSERT OR IGNORE INTO inventory_items (variant_id, quantity_available, quantity_reserved, low_stock_threshold)
SELECT id, 25, 0, 5 FROM product_variants WHERE sku LIKE 'PK-%' AND id NOT IN (SELECT variant_id FROM inventory_items);

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0014_clothing_store_100_products_seed');
